name: Deploy Go Project

on:
  push:
    branches:
      - 'smoreg/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Run testing
#        run: cd test && go test -v

      - name: Copy files via scp
        env:
          $FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}
        run: |
          mkdir -p ~/.ssh
          echo "$FZ_ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ping -c 1 64.227.168.9
          scp -o StrictHostKeyChecking=no myapp deploy@64.227.168.9:/path/to/deploy

      - name: Restart application on server
        env:
          FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}
        run: |
          ssh -o StrictHostKeyChecking=no deploy@64.227.168.9 "sudo systemctl restart yourapp.service"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      
