name: Deploy Go Project

on:
  push:
    branches:
      - 'smoreg/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Run testing
#        run: cd test && go test -v
      #
      #      - name: Run vet & lint
      #        run: |
      #          go vet .
      #          golint .
      #
      #

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build -o freezino_backend_app cmd/*.go

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$FZ_ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}

      - name: Copy files via scp
        run: |
          scp -o StrictHostKeyChecking=no freezino_backend_app deploy@64.227.168.9:/opt/freezino_backend

      - name: Restart application on server
        env:
          FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}
        run: |
          ssh -o StrictHostKeyChecking=no deploy@64.227.168.9 "sudo systemctl restart freezino_backend.service"
