name: Deploy Go Project

on:
  push:
    branches:
      - 'smoreg/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$FZ_ID_RSA" > ~/.ssh/id_rsa
          wc ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}

      - name: Test SCP
        run: |
          echo ho > ho
          ls -l ~/.ssh
          file ~/.ssh/id_rsa
          head -n 5 ~/.ssh/id_rsa
          
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ho deploy@64.227.168.9:~
        env:
          FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}

#      - name: Checkout repository
#        uses: actions/checkout@v2

#      - name: Run testing
#        run: cd test && go test -v
#
#      - name: Copy files via scp
#        env:
#          $FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}
#        run: |
#          mkdir -p ~/.ssh
##         echo "$FZ_ID_RSA" > ~/.ssh/id_rsa
#          echo "$FZ_ID_RSA" | tr -d '\r' | tr '_' '\n' > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          echo ho > ho
#          ls -l ~/.ssh
#          file ~/.ssh/id_rsa
#          cat ~/.ssh/id_rsa
#          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ho deploy@64.227.168.9:~
#
#      - name: Restart application on server
#        env:
#          FZ_ID_RSA: ${{ secrets.FZ_ID_RSA }}
#        run: |
#          ssh -o StrictHostKeyChecking=no deploy@64.227.168.9 "sudo systemctl restart yourapp.service"
#
#      - name: Setup Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.21'
#
#      - name: Install dependencies
#        run: |
#          go version
#          go get -u golang.org/x/lint/golint
#
#      - name: Run build
#        run: go build .
#
#      - name: Run vet & lint
#        run: |
#          go vet .
#          golint .
#
#
